### ISSUE TITLE
run python extract.py --dataset llcm --method agw --gpu 0，the program reported an error

### ISSUE THREAD

**Issue by HFUT00812** [ZYK100/LLCM#18]
![image](https://github.com/ZYK100/LLCM/assets/98513801/e4e9151a-bf7e-4d93-8f9f-d1ac406a79da)

**Comment by ZYK100** [comment]
您好，您需要把DEEN所输出的三个分支的特征进行torch.cat()。

**Comment by Danee-wawawa** [comment]
您好，我也遇到了这个问题，想问下您是如何解决的呢？

**Comment by Danee-wawawa** [comment]
您好，想问下这个操作是在哪里进行呢？

**Comment by vk-rrr** [comment]
修改函数extract_query_feat()下面的两行，
query_feat_pool[ptr:ptr + batch_num, :] = feat_pool[:batch_num, :].detach().cpu().numpy()
query_feat_fc[ptr:ptr + batch_num, :] = feat_fc[:batch_num, :].detach().cpu().numpy()

**Comment by Danee-wawawa** [comment]
好的，感谢~~我看了下，这样的话每次都只会取DEEN所输出的三个分支中的第一个，会不会对结果会有影响呢？
 @ZYK100 辛苦帮忙看下这个问题~

**Comment by GG0614** [comment]
> 修改extract.py里，函数extract_query_feat()下面的两行， query_feat_pool[ptr:ptr + batch_num, :] = feat_pool[:batch_num, :].detach().cpu().numpy() query_feat_fc[ptr:ptr + batch_num, :] = feat_fc[:batch_num, :].detach().cpu().numpy()

你好，我按照你这个修改方式进行修改了，但出现了这种错误
Traceback (most recent call last):
  File "extract.py", line 213, in <module>
    query_feat_pool, query_feat_fc = extract_query_feat(query_loader)
  File "extract.py", line 118, in extract_query_feat
    query_feat_pool[ptr:ptr + batch_num, :] = feat_pool[:batch_num, :].detach().cpu().numpy()
UnboundLocalError: local variable 'feat_pool' referenced before assignment
